theme: jekyll-theme-minimal
title: Git Intro
description: This is created as a short guide to get one started with using git. It covers the most common and vital commands that are used in day to day software development. We will also use the vocabulary that developers use.
